// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHAQnLkrOVWBvQZeogHQWZxAxS2MOkqgA',
    appId: '1:588089643055:web:e7a2c6d5c83ce1c970f6da',
    messagingSenderId: '588089643055',
    projectId: 'jeams-mynotes',
    authDomain: 'jeams-mynotes.firebaseapp.com',
    storageBucket: 'jeams-mynotes.appspot.com',
    measurementId: 'G-BPZ94VKPH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpTwRIwhZqZtxM5F5LhbhH55Wm82iy-4',
    appId: '1:588089643055:android:0e5b447d52dfda2270f6da',
    messagingSenderId: '588089643055',
    projectId: 'jeams-mynotes',
    storageBucket: 'jeams-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDXRqFDqUogWfNEQ2MA_cDUpSwdHUmFA',
    appId: '1:588089643055:ios:709d4b0330aa806270f6da',
    messagingSenderId: '588089643055',
    projectId: 'jeams-mynotes',
    storageBucket: 'jeams-mynotes.appspot.com',
    iosClientId: '588089643055-6rsfnjpb2e0em116o090hh3d247se9j6.apps.googleusercontent.com',
    iosBundleId: 'com.jeams.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDXRqFDqUogWfNEQ2MA_cDUpSwdHUmFA',
    appId: '1:588089643055:ios:709d4b0330aa806270f6da',
    messagingSenderId: '588089643055',
    projectId: 'jeams-mynotes',
    storageBucket: 'jeams-mynotes.appspot.com',
    iosClientId: '588089643055-6rsfnjpb2e0em116o090hh3d247se9j6.apps.googleusercontent.com',
    iosBundleId: 'com.jeams.mynotes',
  );
}
